### ISSUE TITLE
Propose to add drivers as Mbed component

### ISSUE THREAD

**Issue by MarceloSalazar** [ARMmbed/mbed-os-example-for-aws#2]
This concept was tested and introduced in the [mbed-os-example-pelion](https://github.com/ARMmbed/mbed-os-example-pelion) and has been very useful to let us configure drivers and reduce unnecessary compilations. This also helps to reduce the number of files in the root directory and help to scale.

The drivers (lib files) can be added under a [drivers](https://github.com/ARMmbed/mbed-os-example-pelion/tree/master/drivers) folder.

The [mbed_app.json](https://github.com/ARMmbed/mbed-os-example-pelion/blob/master/mbed_app.json#L303) can be used to add these specific components.

@ithinuel @ashok-rao

**Comment by LDong-Arm** [comment]
Also, the .lib file is for ism43362 WiFi module (used on DISCO_L475VG_IOT01A). Other targets/shield may use other WiFi modules, maybe we can link to https://github.com/ARMmbed/mbed-os-example-wifi#supported-hardware for how to import other drivers.

**Comment by ciarmcom** [comment]
@MarceloSalazar it has been 5 days since the last reminder. Could you please update the issue header as previously requested?

**Comment by ciarmcom** [comment]
@MarceloSalazar it has been 5 days since the last reminder. Could you please update the issue header as previously requested?

**Comment by ciarmcom** [comment]
@MarceloSalazar it has been 5 days since the last reminder. Could you please update the issue header as previously requested?

**Comment by ciarmcom** [comment]
@MarceloSalazar it has been 5 days since the last reminder. Could you please update the issue header as previously requested?

**Comment by ciarmcom** [comment]
@MarceloSalazar it has been 5 days since the last reminder. Could you please update the issue header as previously requested?

**Comment by ciarmcom** [comment]
@MarceloSalazar it has been 5 days since the last reminder. Could you please update the issue header as previously requested?
