### ISSUE TITLE
u-blox EVK-ODIN-W2

### ISSUE THREAD

**Issue by Hphipps** [ARMmbed/mbed-os-example-for-aws#34]
### Description of defect
u-blox EVK-ODIN-W2 not supported in mbed 6.

#### Target(s) affected by this defect ?
u-blox EVK-ODIN-W2

#### What version of Mbed-os are you using (tag or sha) ?
6.5

**Comment by ciarmcom** [comment]
@Hphipps thank you for raising this issue.Please take a look at the following comments:

Could you add some more detail to the description? A good description should be at least 25 words.
What toolchain(s) are you using?
We cannot automatically identify a release based on the version of Mbed OS that you have provided.
Please provide either a single valid sha of the form #abcde12 or #3b8265d70af32261311a06e423ca33434d8d80de
or a single valid release tag of the form mbed-os-x.y.z .
E.g. '6.5' has not been matched as a valid tag or sha.It would help if you could also specify the versions of any tools you are using?
How can we reproduce your issue?

NOTE: If there are fields which are not applicable then please just add 'n/a' or 'None'.This indicates to us that at least all the fields have been considered.
Please update the issue header with the missing information, the issue will not be mirroredto our internal defect tracking system or investigated until this has been fully resolved.

**Comment by LDong-Arm** [comment]
Hi @Hphipps, I've seen you raised https://github.com/ARMmbed/mbed-os/issues/13956, so shall I close this one?
